[project]
name = "python-minifier"
version = "3.1.0"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
python-minifier = "python_minifier:main"

[build-system]
requires = ["uv_build>=0.9.2,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "basedpyright>=1.34.0",
    "ruff>=0.14.6",
]
