name: Release Test

on: [push]

permissions:
  contents: none

jobs:

  determine_version:
    name: Determine Version
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    outputs:
      release_version: ${{ steps.set_version.outputs.version }}
    container:
      image: danielflook/python-minifier-build:python3.14-2025-09-26
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          show-progress: false
          persist-credentials: false

      - name: Discover version
        id: set_version
        run: |
          pip3 install setuptools_scm
          VERSION="$(python3 -m setuptools_scm)"
          echo "Version: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

  create_draft_release:
    name: Create Draft Release
    uses: ./.github/workflows/create_draft_release.yaml
    needs:
        - determine_version
    permissions:
      contents: write
    with:
      release_version: ${{ needs.determine_version.outputs.release_version }}
